Update versioning.md
Removed parent::onAfterPublish(); because Page parents does not implement it. The old code generate this error:

Error at framework/core/Object.php line 761: Uncaught Exception: Object->__call(): the method 'onafterpublish' does not exist on 'MyPage' (http://ssdev-master.zk/admin/pages/edit/EditForm)